const projects = [
  {
    name: "pull notes",
    year: "2025",
    format: "digital",
    type: "film",
    length: "",
    role: ["director", "cinematographer", "editor"],
    tools: [],
    shortDescription: "documenting",
    longDescription: "A project in progress. It's been a while (9 years) since I've made a film, so this is me getting back into it. I take my camera on solo day trips and try to be as present, curious, and distractable as possible. I use this as a practice to develop and explore different visual stimuli - I'm a different (kind of) person now, so what pulls me? What am I noticing?",
    screenings: null,
    siteLink: '',
    img: '/birdtree.jpg',
    docImgs: [],
    vidLinks: ['1114419791', '1114419304'],
    slug: "seeing-better",
  },
   {
    name: "currents.school",
    year: "2025",
    format: "",
    type: "web",
    length: "",
    role: ["web developer"],
    tools: ['next.js'],
    shortDescription: "a diy film school",
    longDescription: "work in progress. a website I created for a diy film school that focuses on experimental filmmaking.",
    screenings: null,
    siteLink: "https://currents.school/",
    img: '/currents.png',
    docImgs: [],
    vidLinks: [],
    slug: "currents-school",
  },
  {
    name: "pixel feed",
    year: "2024",
    format: "",
    type: "web",
    length: "",
    role: ["Full-Stack Developer", "UI/UX Design"],
    tools: ['Javascript', 'HTML', 'CSS'],
    shortDescription: "low-fi, grayscale, pixelated webcam",
    longDescription: "pixel feed renders a low-fi, grayscale, pixelated rendering of your webcam feed and allows users to record and download video.",
    screenings: null,
    siteLink: '',
    img: '/pixelfeed1.png',
    docImgs: [],
    vidLinks: ['1116576405'],
    slug: "pixel-feed",
  },
  {
    name: "pix.ly",
    year: "2023",
    format: "",
    type: "web",
    length: "",
    role: ["Full-Stack Developer", "UI/UX Design"],
    tools: ['React', 'Python', 'Flask', 'PostgreSQL', 'AWS S3'],
    shortDescription: "a photo app with a focus on accessibility",
    longDescription: "Pix.ly is a photo gallery app that allows users to upload photos to their pix.ly board, view metadata (including the camera used and location), contribute custom alt-text for their photos (and learn how to effectively write it!), and download photos. Future implementations will include search functionality, focusing on exif data search.",
    screenings: null,
    siteLink: '',
    img: '/pixly.png',
    docImgs: ['/pixly-upload.png', '/pixly-info.png', '/pixly-detail.png'],
    vidLinks: ['866111085'],
    slug: "pixly",
  },
  {
    name: "tumbling through the hand",
    year: "2023",
    format: "",
    type: "web",
    length: "",
    role: ["Full-Stack Developer", "UI/UX Design"],
    tools: ['Javascript', 'HTML', 'CSS'],
    shortDescription: "markov machine for poetry",
    longDescription: "i built a markov chain that statistically predicts future states of word combination based on a given input. in this project, i use it to recombine poetry.",
    screenings: null,
    siteLink: '',
    img: '/markov1.png',
    docImgs: ['/markov2.png', '/markov3.png', '/markov4.png', '/markov5.png'],
    vidLinks: [],
    slug: "tumbling-through",
  },
  {
    name: "proximity",
    year: "2021",
    format: "digital",
    type: "film",
    length: "1:38",
    role: ["director"],
    tools: [],
    shortDescription: "a rotoscope film about cinephilia and film school",
    longDescription: "Me to Agnès Varda: 'I wrote my thesis on Cléo - I've seen that film over 20 times.' Agnès: 'That's more times than I've seen it.' A rotoscope reflection on cinephilia and seven years of film school.",
    screenings: [`"Animation Showcase IV," GAZE film series, Artists' Television Access, San Francisco CA (Oct '19)`],
    siteLink: '',
    img: '/proximity1.jpg',
    docImgs: [],
    vidLinks: ["302709978"],
    slug: "proximity",
  },
  {
    name: "2076 (elegy)",
    year: "2016",
    format: "16mm",
    type: "film",
    length: "5:40",
    role: ["director"],
    tools: ['bolex reflex 16mm', 'kodak 400T', 'kodak 200D'],
    shortDescription: "familial history and queer identity communicated through the archive",
    longDescription: "in the year 2076, a cyborg finds moving images taken by their great-grandparent in the last years of celluloid. looking at the images, they are struck by the past, causing them to dig into their own memories, history, and identity.",
    screenings: [`Canadian Filmmakers Distribution Centre, Distributer, 2017-2022`, `Collectif Jeune Cinéma, Distributor, 2017`, `"Queer, Queen Women," Festival des Cinémas Différents et Expérimentaux de Paris, Paris FR (Oct '19)`, `"Body Images," Labocine/Imagine Science May Issue (#34), Streaming Online (May '19)`, `"Carry Forward," Dunlop Art Gallery, Regina SK, Canada (Oct '18- Jan '19)`, `"Images of Future Past," Loud & Proud, La Gaîte Lyrique, Paris FR (July '17)`, `32nd Lovers Film Festival, Torino International GLBT Film Festival, Turin IT (June '17)`, `"Hamburg X Brighton," Brighton Film Club, Presuming Ed's, Brighton UK (May '17)`, `"a great unknown trust," Crossroads Film Festival, SFMOMA, San Francisco CA (May '17)`, `"The Permanent Perception," BFI Flare London LGBT Film Festival, London UK (March '17)`, `MixNYC Queer Experimental Film Festival, Brooklyn NY (Feb '17)`, `"Environmental Estrangement," Aggregate Space Gallery, Oakland CA (Jan '17)`, `SFSU MFA Thesis Film Showcase, Coppola Theater, San Francisco CA (May '16)`],
    siteLink: '',
    img: '/elegy1.jpg',
    docImgs: ['/elegy2.jpg', '/elegy3.png', '/elegy1.jpg'],
    vidLinks: [],
    slug: "2076-elegy",
  },
  {
    name: "the problem is...",
    year: "2016",
    format: "digital",
    type: "film",
    length: "1:00",
    role: ["director"],
    tools: [],
    shortDescription: "poetry film about love, anxiety, and the cosmos",
    longDescription: "a poetry film written as part of a larger renga project with my MFA cohort. I drew the final number in the chain of ten 1 minute films, and was tasked with creating a film that commented on all nine that came before it. I wove together images and emotions from the previous films to create this piece about love, anxiety, and the cosmos. ",
    screenings: [`"certainty is becoming our nemesis", Orlando, McEvoy Foundation for the Arts, San Francisco CA (Feb-May 2020)`, `SF Cinematheque Crossroads Film Festival (traveling), Minneapolis MN (Jul '16)`, `SF Cinematheque Crossroads Film Festival, San Francisco CA (Apr '16)`],
    siteLink: '',
    img: '/theproblemis.png',
    docImgs: [],
    vidLinks: ['128536567'],
    slug: "the-problem-is",
  },
  {
    name: "delighted by your alchemy",
    year: "2014",
    format: "16mm",
    type: "film",
    length: "5:18",
    role: ["director"],
    tools: ['bolex reflex 16mm', 'kodak b&w negative'],
    shortDescription: "i remember i told you the universe looks like a whole lot of something up close, but now i feel like i am orbiting around it.",
    longDescription: "this film explores the memory of my first queer relationship - shot while we were still together, edited after separating. the film became a project in remembering and refiguring, using superimposition to unsettle and blur the boundary between myself and my new ex.",
    screenings: [`Collectif Jeune Cinéma, Distributor, 2014`, `10th Gay Games, Festival Courts sur Cour, Paris FR (Aug '18)`, `Queer Yo Mind Conference, San Francisco State University CA (Nov '17)`, `"Suspended Belief: 9 Films from Northern California," EXiS Festival 2017, Seoul SKR (July '17)`, `"Transcend", Body + Camera Festival, Mana Contemporary, Chicago IL (May '17)`, `"What's Your Flavor?" Festival Cinémarges, Bourdeaux FR (Apr '17)`, `Collectif Jeune Cinema Showcase, What the F*** Fest, Paris FR (Jul '16)`, `Queer City Cinema Film Festival, Saskatchewan Canada (May '15)`, `BFI Flare: London International LGBT Film Festival, London UK (Mar '15)`, `Gaze Series, Artists' Television Access, San Francisco CA (Feb '15)`, `Alternative Visions, Pacific Film Archive, Berkeley CA (Nov '14)`, `MixNYC Queer Experimental Film Festival, Brooklyn NY (Nov '14)`, `SFSU Film Finals, Sundance Kabuki, San Francisco CA (June '14)`, `SFSU First Year Film Showcase, Coppola Theater, San Francisco CA (May '14)`],
    siteLink: '',
    img: '/dbya02.jpg',
    docImgs: ['/dbya01.jpg', '/dbya4.jpg', '/dbya02.jpg'],
    vidLinks: [],
    slug: "dbya",
  },
];

export default projects;