const projects = [
  {
    name: "heading outside for it",
    year: "2022",
    format: "digital",
    type: "film",
    length: "3:33",
    role: ["director"],
    categories: [],
    shortDescription: "a film about birds",
    longDescription: "sometimes birds will get you and there's nothing you can do about it.",
    img: '/birdtree.jpg',
    alts: [],
    vidLink: "dfwefwefe.mp4",
    slug: "hedskww",
  },
  {
    name: "2076",
    year: "2022",
    format: "digital",
    type: "film",
    length: "3:33",
    role: ["director"],
    categories: [],
    shortDescription: "a film about birds",
    longDescription: "sometimes birds will get you and there's nothing you can do about it.",
    img: '/birdtree.jpg',
    alts: [],
    vidLink: "dfwefwefe.mp4",
    slug: "hedskww",
  },
  {
    name: "somewhere else",
    year: "2022",
    format: "digital",
    type: "photography",
    length: "3:33",
    role: ["director"],
    categories: [],
    shortDescription: "a film about birds",
    longDescription: "sometimes birds will get you and there's nothing you can do about it.",
    img: '/birdtree.jpg',
    alts: [],
    vidLink: "dfwefwefe.mp4",
    slug: "hedskww",
  },
   {
    name: "currents.school",
    year: "2025",
    format: "digital",
    type: "website",
    length: "3:33",
    role: ["director"],
    categories: [],
    shortDescription: "a film about birds",
    longDescription: "sometimes birds will get you and there's nothing you can do about it.",
    img: '/birdtree.jpg',
    alts: [],
    vidLink: "dfwefwefe.mp4",
    slug: "hedskww",
  },
   {
    name: "raccoon cowboy",
    year: "2025",
    format: "digital",
    type: "website",
    length: "3:33",
    role: ["director"],
    categories: [],
    shortDescription: "a film about birds",
    longDescription: "sometimes birds will get you and there's nothing you can do about it.",
    img: '/birdtree.jpg',
    alts: [],
    vidLink: "dfwefwefe.mp4",
    slug: "hedskww",
  },
];

export default projects;